package com.demo.uber.helperservice.model;

public enum OnboardingStatus {
    ACCOUNT_CREATED,
    PROFILE_INFO_ADDED,
    DOCUMENTS_COLLECTED,
    BACKGROUND_VERIFICATION_INPROGRESS,
    BACKGROUND_VERIFICATION_COMPLETED,
    DEVICE_SHIPPED;
}
